### ISSUE TITLE
Cannot display the contributions in saved image

### ISSUE THREAD

**Issue by JanisZhang** [Codennnn/Green-Wall#12]
Hi LeoKu!
It seems to have some issues in the saved contributions image. (Ubuntu 21.10+Google Chrome)
![image](https://user-images.githubusercontent.com/95570096/191408926-997b3d9e-a5f8-40d9-975c-5008f9a47349.png)

**Comment by Codennnn** [comment]
Since I don't have the operating system like yours, I could not reproduce the BUG  :(

I guess this is because the dependency `html-to-image` I'm using has a compatibility issue.

**Comment by JanisZhang** [comment]
Noted :) 
Thank you for the reply and the awesome work! I'm gonna close this
