### ISSUE TITLE
contribution count is not correct

### ISSUE THREAD

**Issue by faga1** [Codennnn/Green-Wall#8]
contribution count is less than contributions in my profile.And can I get my last year contributions,I think it's useful

**Comment by faga1** [comment]
Can I get picture through github actions(like https://github.com/pomber/stargazer)?If you want,I recommend myself to submit a pull request

**Comment by faga1** [comment]
It's probably due to private repository

**Comment by Codennnn** [comment]
> Can I get picture through github actions(like https://github.com/pomber/stargazer )? I think I can submit a pull request to implement it

That's a good idea! It would be great if you could help.
